### ISSUE TITLE
这个扩展什么原理

### ISSUE THREAD

**Issue by happmaoo** [lqzhgood/wechat-need-web#10]

**Comment by lly-ke** [comment]
应该就是伪造请求参数让微信识别不了吧,  代码主要就一个`wx-rules.json`文件

**Comment by lly-ke** [comment]
<img width="769" alt="image" src="https://github.com/lqzhgood/wechat-need-web/assets/28623614/dc43d92b-4a25-4d3b-92d5-6aa4f740bc62">

**Comment by lqzhgood** [comment]
简单点说，微信要支持创信客户端，就用浏览器套壳整了一个，这个插件模拟那个壳，注入一些参数。

**Comment by happmaoo** [comment]
> `wx-rules.json` 两个配置项的解释
> 
> <img alt="image" width="769" src="https://private-user-images.githubusercontent.com/28623614/290965444-dc43d92b-4a25-4d3b-92d5-6aa4f740bc62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MjIxMTEsIm5iZiI6MTcwMjcyMTgxMSwicGF0aCI6Ii8yODYyMzYxNC8yOTA5NjU0NDQtZGM0M2Q5MmItNGEyNS00ZDNiLTkyZDUtNmFhNGY3NDBiYzYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDEwMTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkOTM2YzlhZDAwM2I5YjRmMTE4YmU2MzBmODYyNzVjNzkyMDZiYWIzMDU5NzY4ODNiMTc1NzY3OTAzZTI2NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T1J2Xf1Bs-TEyWyaVdZuNoHKsHXJ8sg8P7uEoHWCipU">

gpt真牛逼
