### ISSUE TITLE
NB

### ISSUE THREAD

**Issue by ZHAIXINGZHAIYUE** [lqzhgood/wechat-need-web#13]
忍不住要夸你一句，NB！

**Comment by wojiushixiaobai** [comment]
大佬 6666。

**Comment by Kiswelrg** [comment]
can anyone tell me how to use this after downloading release files

**Comment by wojiushixiaobai** [comment]
@Kiswelrg https://developer.chrome.com/docs/extensions/get-started/tutorial/hello-world#load-unpacked

**Comment by lqzhgood** [comment]
这是互夸环节么?

龙年到了,  夸夸楼上各位 LB~    ;)

**Comment by Kiswelrg** [comment]
> @Kiswelrg See.
> 
> * https://developer.chrome.com/docs/extensions/get-started/tutorial/hello-world#load-unpacked

哦感谢老哥 wx那个网页版必须弄个插件才能用啊 离谱
