### ISSUE TITLE
firefox显示:附加组件无法安装，因为它似乎已损坏。

### ISSUE THREAD

**Issue by chenxuan520** [lqzhgood/wechat-need-web#14]
# 复现方法
1. 版本为截止2024.02.25最新版本
2. firefox版本为
![图片](https://github.com/lqzhgood/wechat-need-web/assets/77540051/19e499ee-f740-4de9-9d60-1d15b259798b)
3. 点击.xpi安装,显示错误(附加组件无法安装，因为它似乎已损坏。)
# 失败方法
- [参考](https://www.jianshu.com/p/4979f6c028c4)中操作无效
![图片](https://github.com/lqzhgood/wechat-need-web/assets/77540051/197ef73d-01b4-40de-8d54-1f34c84e99b0)

**Comment by lqzhgood** [comment]
你这更新都写的被禁用了....

官网下载的 116 测试正常.

![image](https://github.com/lqzhgood/wechat-need-web/assets/9134671/31e3ac49-c3a1-48bd-8fe8-0b3540979018)
