### ISSUE TITLE
need help新手小白

### ISSUE THREAD

**Issue by eileenwang2007** [lqzhgood/wechat-need-web#17]
hi I am a newcomer for this website, i use chromebook and after I open for chrome zip, it takes me to the txt one, and I do not know what to do next.
 你好我用的是chromebook，打开zip后跳转到了txt，之后就不知道怎么做了，新手小白求助

**Comment by lqzhgood** [comment]
参考这个吧
https://blog.51cto.com/u_15823091/5745191
