### ISSUE TITLE
碰到两个问题

### ISSUE THREAD

**Issue by Jerryyuanyuan** [lqzhgood/wechat-need-web#20]
操作系统：Arch下的Endeavor OS
![图片](https://github.com/lqzhgood/wechat-need-web/assets/18299433/2ac78cfb-fa27-476f-8439-d75ebfeaef4b)
浏览器：FireFox 123.0.1（64位）
![图片](https://github.com/lqzhgood/wechat-need-web/assets/18299433/0056c042-60b7-4091-9954-81d7dbbeb00c)
插件版本：1.1.1
![图片](https://github.com/lqzhgood/wechat-need-web/assets/18299433/db755b87-f4a3-418c-9178-a3fd3fe66592)

碰到两个问题：
1、左侧聊天框无法上下翻动，只能通过搜索进行聊天人选择。
2、使用Spectacle截图，无法直接粘贴发送。

**Comment by lqzhgood** [comment]
本插件仅处理登录问题,  网站兼容性问题找腾讯~

**Comment by hao7Chen** [comment]
我也遇到了，用 edge 或者 chrome 就不会
