### ISSUE TITLE
不能使用了

### ISSUE THREAD

**Issue by juvaliu** [lqzhgood/wechat-need-web#24]
现在2024-03-25已经不能登录了，请知悉！

**Comment by jdymss** [comment]
正常使用

**Comment by jdymss** [comment]
> 现在2024-03-25已经不能登录了，请知悉！
正常使用

**Comment by lqzhgood** [comment]
正常使用

**Comment by LUKE-GG33** [comment]
如果是使用火狐浏览器的话，打开这些权限权限就可以使用了
![1](https://github.com/lqzhgood/wechat-need-web/assets/35057228/16f72f8f-fd9d-41a2-9f6e-e370b2113cae)
