### ISSUE TITLE
需要“同步最近消息”这个功能

### ISSUE THREAD

**Issue by QiuLiang-99** [lqzhgood/wechat-need-web#25]
如果消息发出之后才登陆的话之前的消息完全接受不到。与此相对的是微信电脑版在扫码登陆之后手机微信的确认界面有一个选项“同步最近消息”，如果勾选了这个选项就可以同步消息。但是这个插件创造的二维码没有这个选项

**Comment by lqzhgood** [comment]
这个插件的作用是允许你登录 **官方** web 微信.
web 微信的功能多少由官方实现.
