### ISSUE TITLE
Firefox 不能调用系统剪切板

### ISSUE THREAD

**Issue by Thesoul20** [lqzhgood/wechat-need-web#26]
在使用Firefox 登陆微信网页版的时候，不能使用系统的剪切板，不能粘贴剪切板中的文字与图像。已经开启插件的全部权限：
![image](https://github.com/lqzhgood/wechat-need-web/assets/49742133/0d380483-0484-48bf-b9ab-d436c53111ce)

但是在Chrome 中就可以正常的使用系统剪切板。

Firefox 版本：
![image](https://github.com/lqzhgood/wechat-need-web/assets/49742133/5b70943e-c384-4eeb-833e-ae3d5e950132)

系统版本：
操作系统： Kubuntu 22.10
KDE Plasma 版本： 5.25.5
KDE 程序框架版本： 5.98.0
Qt 版本： 5.15.6
内核版本： 5.19.0-46-generic (64-位)
图形平台： X11
处理器： 20 × 13th Gen Intel® Core™ i5-13600KF
内存： 31.1 GiB 内存
图形处理器： NVIDIA GeForce RTX 3060/PCIe/SSE2
制造商： ASUS

**Comment by lqzhgood** [comment]
本插件仅处理登录问题, 且未对网站有任何修改. 原网站的兼容性问题不处理.
