### ISSUE TITLE
项目有封号风险

### ISSUE THREAD

**Issue by jianboy** [lqzhgood/wechat-need-web#30]
地球不允许使用web版本，但却web网页版一直特供存在。少数人的特权，大家想要使用本项目会被封号。

![image](https://github.com/user-attachments/assets/d735dce0-1733-40dd-80a4-c34ba9883079)

**Comment by lqzhgood** [comment]
您是使用了本项目导致被封了么?

**Comment by ShengHuaHH** [comment]
> 您是使用了本项目导致被封了么?
> 
> 本项目是官方出的 web 版本.

同问
![1750427477](https://github.com/user-attachments/assets/c8dfe91e-c864-4c95-a8af-ec09111b759c)

**Comment by tedonggo** [comment]
吓 不尬登陆了 还是用多开吧 就是费内存🥱

**Comment by Roelatriper** [comment]
这情况很常见吗？

**Comment by lqzhgood** [comment]
本项目是官方 web 版, 未添加任何其他脚本. 
web 版官方未禁止也未允许. 所以使用上自己评估吧.

如果只是因为 "地球不允许使用web版本" 没有实质的东西  这个 issue 先关了~
