### ISSUE TITLE
Wechat web requires enable wechat pay

### ISSUE THREAD

**Issue by shenzhenadam** [lqzhgood/wechat-need-web#34]
Wechat web requires to enable wechat pay - I have enabled wechat pay - but it still asks to enable it - I don't want to download the app - so what's the solution now for getting wechat web to work on a browser??

Thanks!

![image](https://github.com/user-attachments/assets/dac15d3a-33a7-44fe-9340-f90ead9d9dd6)

**Comment by lqzhgood** [comment]
I don't know either, this may be some kind of official restriction, but the prompt is incorrect.

**Comment by ASUEFUN** [comment]
插件无法使用了已经

**Comment by lqzhgood** [comment]
> 插件无法使用了已经

测试正常
