### ISSUE TITLE
打不开了😨😨

### ISSUE THREAD

**Issue by LUlu0113** [lqzhgood/wechat-need-web#38]
登录自动转到https://wx.qq.com/?target=t
然后网页就是一片黑。
之前一直都可以用的，突然就这样了。。。

![image](https://github.com/user-attachments/assets/8650028b-9c93-4bc6-bef4-bf684344dac9)
求问这是什么意思啊

**Comment by debuggerzh** [comment]
你试下硬刷新

**Comment by Mkxoo** [comment]
同款问题 硬刷新也没用欸

**Comment by lqzhgood** [comment]
我测试 ok 呀。

Microsoft Edge
版本 131.0.2903.70 (正式版本) (64 位)

Chrome
版本 118.0.5993.89（正式版本） （64 位）

**Comment by lqzhgood** [comment]
从图中看到是 460.js 这个文件的警告，但是我查看了所有请求， 并没有这个文件。 
大概率是你的浏览器其他插件造成的影响。
