### ISSUE TITLE
[Bug] 登录失败

### ISSUE THREAD

**Issue by helloworldSB** [lqzhgood/wechat-need-web#4]
弹出 “1203 登录失败” 的弹窗

初步猜测，bug 可能是因为：
1. `?target=t` 只能在根页面加
2. 自定义Header 只应当在 `/cgi-bin/mmwebwx-bin/webwxnewloginpage` 增加

**Comment by lqzhgood** [comment]
我这登录 wx.qq.com 正常，请提供复现步骤~

**Comment by helloworldSB** [comment]
> 我这登录 wx.qq.com 正常，请提供复现步骤~

1. 登录
2. 退出登录（如果正常登录请清除cookie）
3. 使用不同账户，重新登录

**Comment by lqzhgood** [comment]
2 什么意思？  退出登录又清除 cookie ，那么不是等于 1 么~

**Comment by helloworldSB** [comment]
> 2 什么意思？ 退出登录又清除 cookie ，那么不是等于 1 么~

应该会记录IP吧（？

**Comment by lqzhgood** [comment]
1. wx.qq.com 登录A
2. 网页中点击退出登录
3. 清除 cookies  / 不清除 cookies
4. 页面自动退回到 https://wx2.qq.com/?=&lang=zh_CN&target=t
5. 登录 B
6. 正常登录


我测试正常


Firefox 插件不与 Chrome 100% 兼容，是不是 firebox 的问题
