### ISSUE TITLE
希望能支持Firefox

### ISSUE THREAD

**Issue by asibelieve** [lqzhgood/wechat-need-web#5]
RT

**Comment by lqzhgood** [comment]
代码符合 v3 规范~

Firefox 看看是不是权限问题

参考
https://stackoverflow.com/questions/76521184/modifyheaders-with-updatedynamicrules-doesnt-work-on-firefox-using-manifest-v3

https://discourse.mozilla.org/t/modifyheaders-with-updatedynamicrules-doesnt-work-on-firefox-using-manifest-v3/120530/2

**Comment by lqzhgood** [comment]
是 Firefox 的 Bug~ 对一个网站只能匹配一个规则.....
提交问题到社区了~  看会不会改吧

https://discourse.mozilla.org/t/cannot-match-multiple-rules-on-the-same-website-on-firefox-using-manifest-v3/123306

**Comment by lqzhgood** [comment]
https://github.com/lqzhgood/wechat-need-web/issues/4
same as

**Comment by lqzhgood** [comment]
研究了一下，核心点在于规范并未明确多条规则匹配时浏览器的处理方式，也不能算 bug 吧。

firefox 选择仅匹配优先级最高的一条（类型：重定向优先  > `priority` 字段）
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/declarativeNetRequest#matching_precedents

chrome 选择全部匹配 ( priority > 类型)
https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#implementation-matching-algorithm



firefox 单独写了一套，使用内嵌 js 的方式绕过限制，会多一个 `scripting` 的权限，加载一个脚本（Chrome 0 脚本）。 其余效果一致。

**Comment by dev-techmoe** [comment]
有没有考虑把这个插件发布到 https://addons.mozilla.org/ ？

如果不想上架的话，看起来插件需要走firefox签名一下，之后可以选择自己分发而不展示到商店里。

https://extensionworkshop.com/documentation/publish/signing-and-distribution-overview

**Comment by lqzhgood** [comment]
@dev-techmoe 文档内有~

**Comment by lqzhgood** [comment]
是放到 Releases 里去了
