### ISSUE TITLE
Chrome Extension Added but not working

### ISSUE THREAD

**Issue by fligit** [lqzhgood/wechat-need-web#6]
加载进入了chrome extension from developer mode
但是还是不work

我看到你们document里有两个像hash一样的字符串，是有什么作用吗？

**Comment by lqzhgood** [comment]
你能描述详细一点么……

不知道在说啥~

**Comment by fligit** [comment]
那能详细描述下怎么使用的吗

我下载了release最新文件，解压，然后在chrome里打开developer mode加载了extension
去网页版微信 扫码登陆，还是遇到同样的问题

**Comment by lqzhgood** [comment]
哪个网站~ 是 wx.qq.com 吗

**Comment by fligit** [comment]
嗯 wx.qq.com 这个试过 其它几个我看你们extension里support的也试了下。都不work for me

**Comment by fligit** [comment]
https://github.com/lqzhgood/wechat-need-web/wiki

这里面那串字符有用吗？

**Comment by lqzhgood** [comment]
Chrome 版本号是多少？

进入 wx.qq.com 后地址栏是否有自动跳转到 https://wx.qq.com/?target=t

**Comment by fligit** [comment]
User Agent | 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) 
AppleWebKit/537.36 (KHTML, like Gecko) 
Chrome/118.0.0.0 
Safari/537.36

有自动跳转到上面的地址

**Comment by lqzhgood** [comment]
我测试了一下最新版是可以的
> Edge 版本 118.0.2088.46 (正式版本) (64 位)

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.46

> Chrome 版本 118.0.5993.89（正式版本） （64 位）

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

应该和 Mac 没关系吧~

你尝试 **只让** wechat-need-web 在无痕模式启用，然后通过无痕模式 打开 wx.qq.com 试试~  排除一下其他扩展可能导致的问题

**Comment by lqzhgood** [comment]
正常情况
打开 wx.qq.com 会自动跳转 https://wx.qq.com/?target=t
https://wx.qq.com/?target=t 的 header 头会有 `Extspam`

**Comment by fligit** [comment]
无痕模式还是不行

**Comment by lqzhgood** [comment]
那我就不知道了， 我手上没有 MAC 无法测试
