### ISSUE TITLE
请问通过这个，能使用EFB转接信息到Telegram吗

### ISSUE THREAD

**Issue by CaptNo78** [lqzhgood/wechat-need-web#9]
目前的EFB-WeChat-Slave还是用的网页版微信，如果通过这个软件登录成功网页端，能否EFB那头也能用了呀

**Comment by lqzhgood** [comment]
这个 commit 就用过了 https://github.com/ehForwarderBot/efb-wechat-slave/commit/8312b767f47328f8da3a83817c51e59190815322

详见 https://github.com/ehForwarderBot/efb-wechat-slave/issues/7

不清楚为什么不用了
